/****************************************************
 *      CLSCTRS.H                                   *
 *  Copyright (C) Михаил М. Баранов                 *
 *  Модификация без предварительного согласия автора*
 *  будет рассматривается как нарушение авторского  *
 *  и имущественного права                          *
 *  создан: 21 Сентября 1995, Четверг               *
 ****************************************************/
#ifndef F8
#define F8

//-- DDF file generator (c) 1994 --

//X$Classificator (clsctrs.ddf)
struct file_8 {
  short               id                       ; //id
  short               item                     ; //item
  char                name                [31] ; //name
};

struct file_8_0{
  short               id                       ; //id
  short               item                     ; //item
};
#endif
