/****************************************************
 *       COMMON.H                                   *
 *  Copyright (C) Михаил М. Баранов                 *
 *  Модификация без предварительного согласия автора*
 *  будет рассматривается как нарушение авторского  *
 *  и имущественного права                          *
 *  создан: 21 Сентября 1995, Четверг               *
 ****************************************************/
#ifndef COMMON
#define COMMON
#include <string.h>
#include <dos.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#include "TRACE.H"
#include "MOUSE.H"
#include "STYLES.H"
#include "KEY.H"
#include "MYSTRING.H"
#include "DATE.H"
#include "BBG.H"
#include "SCREEN.H"
#include "MYNEW.H"
#include "EVENT.H"
#include "QUEUE.H"
#include "WINDOW.H"
#include "DESKTOP.H"
#include "VMENU.H"
#include "LOWPRINT.H"
#include "FVIEW.H"
#include "CLSVIEW.H"
#include "CELL.H"
#include "DIGCELL.H"
#include "DATECELL.H"
#include "TIMECELL.H"
#include "SHRTCELL.H"
#include "BYTECELL.H"
#include "FLTCELL.H"
#include "DBLCELL.H"
#include "LDBLCELL.H"
#include "YNCELL.H"
#include "CLSRCELL.H"
#include "CLSBCELL.H"
#include "DDF.H"
#include "HELP.H"
#include "HMENU.H"
#include "MESWIN.H"
#include "BUILDER.H"
#include "RELCCELL.H"
#include "RELSCELL.H"
#include "RELLCELL.H"
#include "GAUGE.H"
#include "LIST.H"
#include "CHOOSE.H"
#endif
