/****************************************************
 *         DDF_.H                                   *
 *  Copyright (C) Михаил М. Баранов                 *
 *  Модификация без предварительного согласия автора*
 *  будет рассматривается как нарушение авторского  *
 *  и имущественного права                          *
 *  создан: 21 Сентября 1995, Четверг               *
 ****************************************************/
struct file_4 {
  short               Relation_id              ; //Relation_id
  short               Part                     ; //Part
  short               Source_file_id           ; //Source_file_id
  short               Source_field_id          ; //Source_field_id
  short               Dest_file_id             ; //Dest_file_id
  short               Dest_index__             ; //Dest_index_#
};

struct file_4_0{
  short               Relation_id              ; //Relation_id
  short               Part                     ; //Part
};

